In [1]:
import sidrapy
import pandas as pd
from pathlib import Path

caminho = Path(r"C:\Users\Felipe\Documents\Python\Clusterizacao_Municipios\dados")

dados = sidrapy.get_table(
    table_code="6803",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022"
)

display(dados.head())
display(dados.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Variável (Código),Variável,Existência de ligação à rede geral de distribu...,Existência de ligação à rede geral de distribu...
1,6,Município,1020,Unidades,7695,1100015,Alta Floresta D'Oeste - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
2,6,Município,1020,Unidades,34768,1100023,Ariquemes - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
3,6,Município,1020,Unidades,1967,1100031,Cabixi - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
4,6,Município,1020,Unidades,31917,1100049,Cacoal - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      5571 non-null   object
 1   NN      5571 non-null   object
 2   MC      5571 non-null   object
 3   MN      5571 non-null   object
 4   V       5571 non-null   object
 5   D1C     5571 non-null   object
 6   D1N     5571 non-null   object
 7   D2C     5571 non-null   object
 8   D2N     5571 non-null   object
 9   D3C     5571 non-null   object
 10  D3N     5571 non-null   object
 11  D4C     5571 non-null   object
 12  D4N     5571 non-null   object
dtypes: object(13)
memory usage: 565.9+ KB

None

In [2]:
dados.columns = dados.iloc[0]
dados = dados.iloc[1:]

display(dados.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Variável (Código),Variável,Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água (Código),Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água
1,6,Município,1020,Unidades,7695,1100015,Alta Floresta D'Oeste - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
2,6,Município,1020,Unidades,34768,1100023,Ariquemes - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
3,6,Município,1020,Unidades,1967,1100031,Cabixi - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
4,6,Município,1020,Unidades,31917,1100049,Cacoal - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total
5,6,Município,1020,Unidades,5873,1100056,Cerejeiras - RO,2022,2022,381,Domicílios particulares permanentes ocupados,72129,Total

In [3]:
dados = dados.rename(columns={'Município (Código)': 'cod_municipio', 'Município': 'municipio', 'Valor': 'total_domicilios'})
dados['total_domicilios'] = pd.to_numeric(dados['total_domicilios'])

dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 1 to 5570
Data columns (total 13 columns):
 #   Column                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                          --------------  -----
 0   Nível Territorial (Código)                                                                                      5570 non-null   object
 1   Nível Territorial                                                                                               5570 non-null   object
 2   Unidade de Medida (Código)                                                                                      5570 non-null   object
 3   Unidade de Medida                                                                                               5570 non-null   object
 4   total_domicilios                                                                                                5570 non-null   int64
 5   cod_municipio                                                                                                   5570 non-null   object
 6   municipio                                                                                                       5570 non-null   object
 7   Ano (Código)                                                                                                    5570 non-null   object
 8   Ano                                                                                                             5570 non-null   object
 9   Variável (Código)                                                                                               5570 non-null   object
 10  Variável                                                                                                        5570 non-null   object
 11  Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água (Código)  5570 non-null   object
 12  Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água           5570 non-null   object
dtypes: int64(1), object(12)
memory usage: 565.8+ KB

In [4]:
dados = dados[['cod_municipio', 'municipio', 'total_domicilios']]

display(dados.head())

0 cod_municipio                   municipio  total_domicilios
1       1100015  Alta Floresta D'Oeste - RO              7695
2       1100023              Ariquemes - RO             34768
3       1100031                 Cabixi - RO              1967
4       1100049                 Cacoal - RO             31917
5       1100056             Cerejeiras - RO              5873

In [5]:
import requests

response = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/6803/metadados")
metadados = response.json()
display(metadados['classificacoes'])

[{'id': 1821,
  'nome': 'Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 72129, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 72144,
    'nome': 'Possui ligação à rede geral e a utiliza como forma principal',
    'unidade': None,
    'nivel': 1},
   {'id': 72145,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma',
    'unidade': None,
    'nivel': 1},
   {'id': 72146,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Poço profundo ou artesiano',
    'unidade': None,
    'nivel': 2},
   {'id': 72147,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Poço raso, freático ou cacimba',
    'unidade': None,
    'nivel': 2},
   {'id': 72148,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Fonte, nascente ou mina',
    'unidade': None,
    'nivel': 2},
   {'id': 72149,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Carro-pipa',
    'unidade': None,
    'nivel': 2},
   {'id': 72150,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Água da chuva armazenada',
    'unidade': None,
    'nivel': 2},
   {'id': 72151,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Rios, açudes, córregos, lagos e igarapés',
    'unidade': None,
    'nivel': 2},
   {'id': 72152,
    'nome': 'Possui ligação à rede geral, mas utiliza principalmente outra forma - Outra',
    'unidade': None,
    'nivel': 2},
   {'id': 72153,
    'nome': 'Não possui ligação com a rede geral',
    'unidade': None,
    'nivel': 1},
   {'id': 72154,
    'nome': 'Não possui ligação com a rede geral - Poço profundo ou artesiano',
    'unidade': None,
    'nivel': 2},
   {'id': 72155,
    'nome': 'Não possui ligação com a rede geral - Poço raso, freático ou cacimba',
    'unidade': None,
    'nivel': 2},
   {'id': 72156,
    'nome': 'Não possui ligação com a rede geral - Fonte, nascente ou mina',
    'unidade': None,
    'nivel': 2},
   {'id': 72157,
    'nome': 'Não possui ligação com a rede geral - Carro-pipa',
    'unidade': None,
    'nivel': 2},
   {'id': 72158,
    'nome': 'Não possui ligação com a rede geral - Água da chuva armazenada',
    'unidade': None,
    'nivel': 2},
   {'id': 72159,
    'nome': 'Não possui ligação com a rede geral - Rios, açudes, córregos, lagos e igarapés',
    'unidade': None,
    'nivel': 2},
   {'id': 72160,
    'nome': 'Não possui ligação com a rede geral - Outra',
    'unidade': None,
    'nivel': 2}]}]

In [6]:
dados_agua = sidrapy.get_table(
    table_code="6803",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022",
    classifications={"1821": "72144"}
)

display(dados_agua.head())
display(dados_agua.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Existência de ligação à rede geral de distribu...,Existência de ligação à rede geral de distribu...,Variável (Código),Variável
1,6,Município,1020,Unidades,2038,1100015,Alta Floresta D'Oeste - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
2,6,Município,1020,Unidades,18892,1100023,Ariquemes - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
3,6,Município,1020,Unidades,773,1100031,Cabixi - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
4,6,Município,1020,Unidades,25555,1100049,Cacoal - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      5571 non-null   object
 1   NN      5571 non-null   object
 2   MC      5571 non-null   object
 3   MN      5571 non-null   object
 4   V       5571 non-null   object
 5   D1C     5571 non-null   object
 6   D1N     5571 non-null   object
 7   D2C     5571 non-null   object
 8   D2N     5571 non-null   object
 9   D3C     5571 non-null   object
 10  D3N     5571 non-null   object
 11  D4C     5571 non-null   object
 12  D4N     5571 non-null   object
dtypes: object(13)
memory usage: 565.9+ KB

None

In [7]:
dados_agua.columns = dados_agua.iloc[0]
dados_agua = dados_agua.iloc[1:]

display(dados_agua.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água (Código),Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água,Variável (Código),Variável
1,6,Município,1020,Unidades,2038,1100015,Alta Floresta D'Oeste - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
2,6,Município,1020,Unidades,18892,1100023,Ariquemes - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
3,6,Município,1020,Unidades,773,1100031,Cabixi - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
4,6,Município,1020,Unidades,25555,1100049,Cacoal - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados
5,6,Município,1020,Unidades,2906,1100056,Cerejeiras - RO,2022,2022,72144,Possui ligação à rede geral e a utiliza como f...,381,Domicílios particulares permanentes ocupados

In [ ]:
dados_agua = dados_agua.rename(columns={'Município (Código)': 'cod_municipio', 'Município': 'municipio', 'Valor': 'total_domicilios_agua'})
dados_agua['total_domicilios_agua'] = pd.to_numeric(dados_agua['total_domicilios_agua'], errors='coerce')

dados_agua.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 1 to 5570
Data columns (total 13 columns):
 #   Column                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                          --------------  -----
 0   Nível Territorial (Código)                                                                                      5570 non-null   object
 1   Nível Territorial                                                                                               5570 non-null   object
 2   Unidade de Medida (Código)                                                                                      5570 non-null   object
 3   Unidade de Medida                                                                                               5570 non-null   object
 4   total_domicilios_agua                                                                                           5562 non-null   float64
 5   cod_municipio                                                                                                   5570 non-null   object
 6   municipio                                                                                                       5570 non-null   object
 7   Ano (Código)                                                                                                    5570 non-null   object
 8   Ano                                                                                                             5570 non-null   object
 9   Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água (Código)  5570 non-null   object
 10  Existência de ligação à rede geral de distribuição de água e principal forma de abastecimento de água           5570 non-null   object
 11  Variável (Código)                                                                                               5570 non-null   object
 12  Variável                                                                                                        5570 non-null   object
dtypes: float64(1), object(12)
memory usage: 565.8+ KB

In [9]:
dados_agua = dados_agua[['cod_municipio', 'municipio', 'total_domicilios_agua']]

display(dados_agua.head())

0 cod_municipio                   municipio  total_domicilios_agua
1       1100015  Alta Floresta D'Oeste - RO                 2038.0
2       1100023              Ariquemes - RO                18892.0
3       1100031                 Cabixi - RO                  773.0
4       1100049                 Cacoal - RO                25555.0
5       1100056             Cerejeiras - RO                 2906.0

In [ ]:
dados_consolidados = pd.merge(dados, dados_agua, on=['cod_municipio', 'municipio'], how='left')
dados_consolidados['perc_agua_rede'] = (dados_consolidados['total_domicilios_agua'].div(dados_consolidados['total_domicilios'])) * 100
dados_consolidados = dados_consolidados.drop(columns=['total_domicilios_agua'])

display(dados_consolidados.head())

0 cod_municipio                   municipio  total_domicilios  perc_agua_rede
0       1100015  Alta Floresta D'Oeste - RO              7695       26.484730
1       1100023              Ariquemes - RO             34768       54.337322
2       1100031                 Cabixi - RO              1967       39.298424
3       1100049                 Cacoal - RO             31917       80.067049
4       1100056             Cerejeiras - RO              5873       49.480674

In [11]:
import requests

response = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/6805/metadados")
metadados = response.json()
display(metadados['classificacoes'])

[{'id': 11558,
  'nome': 'Tipo de esgotamento sanitário',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 46292, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 46290,
    'nome': 'Rede geral, rede pluvial ou fossa ligada à rede',
    'unidade': None,
    'nivel': 1},
   {'id': 72110, 'nome': 'Rede geral ou pluvial', 'unidade': None, 'nivel': 2},
   {'id': 72111,
    'nome': 'Fossa séptica ou fossa filtro ligada à rede',
    'unidade': None,
    'nivel': 2},
   {'id': 72112,
    'nome': 'Fossa séptica ou fossa filtro não ligada à rede',
    'unidade': None,
    'nivel': 1},
   {'id': 72113,
    'nome': 'Fossa rudimentar ou buraco',
    'unidade': None,
    'nivel': 1},
   {'id': 92858, 'nome': 'Vala', 'unidade': None, 'nivel': 1},
   {'id': 72114,
    'nome': 'Rio, lago, córrego ou mar',
    'unidade': None,
    'nivel': 1},
   {'id': 72115, 'nome': 'Outra forma', 'unidade': None, 'nivel': 1},
   {'id': 92861,
    'nome': 'Não tinham banheiro nem sanitário',
    'unidade': None,
    'nivel': 1}]}]

In [12]:
dados_esgoto = sidrapy.get_table(
    table_code="6805",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022",
    classifications={"11558": "46290"}
)

display(dados_esgoto.head())
display(dados_esgoto.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Tipo de esgotamento sanitário (Código),Tipo de esgotamento sanitário,Variável (Código),Variável
1,6,Município,1020,Unidades,36,1100015,Alta Floresta D'Oeste - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
2,6,Município,1020,Unidades,693,1100023,Ariquemes - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
3,6,Município,1020,Unidades,31,1100031,Cabixi - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
4,6,Município,1020,Unidades,21445,1100049,Cacoal - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      5571 non-null   object
 1   NN      5571 non-null   object
 2   MC      5571 non-null   object
 3   MN      5571 non-null   object
 4   V       5571 non-null   object
 5   D1C     5571 non-null   object
 6   D1N     5571 non-null   object
 7   D2C     5571 non-null   object
 8   D2N     5571 non-null   object
 9   D3C     5571 non-null   object
 10  D3N     5571 non-null   object
 11  D4C     5571 non-null   object
 12  D4N     5571 non-null   object
dtypes: object(13)
memory usage: 565.9+ KB

None

In [13]:
dados_esgoto.columns = dados_esgoto.iloc[0]
dados_esgoto = dados_esgoto.iloc[1:]

display(dados_esgoto.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Tipo de esgotamento sanitário (Código),Tipo de esgotamento sanitário,Variável (Código),Variável
1,6,Município,1020,Unidades,36,1100015,Alta Floresta D'Oeste - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
2,6,Município,1020,Unidades,693,1100023,Ariquemes - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
3,6,Município,1020,Unidades,31,1100031,Cabixi - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
4,6,Município,1020,Unidades,21445,1100049,Cacoal - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados
5,6,Município,1020,Unidades,3406,1100056,Cerejeiras - RO,2022,2022,46290,"Rede geral, rede pluvial ou fossa ligada à rede",381,Domicílios particulares permanentes ocupados

In [14]:
dados_esgoto = dados_esgoto.rename(columns={'Município (Código)': 'cod_municipio', 'Município': 'municipio', 'Valor': 'total_domicilios_esgoto'})
dados_esgoto['total_domicilios_esgoto'] = pd.to_numeric(dados_esgoto['total_domicilios_esgoto'], errors='coerce')

display(dados_esgoto.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 1 to 5570
Data columns (total 13 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nível Territorial (Código)              5570 non-null   object
 1   Nível Territorial                       5570 non-null   object
 2   Unidade de Medida (Código)              5570 non-null   object
 3   Unidade de Medida                       5570 non-null   object
 4   total_domicilios_esgoto                 5545 non-null   float64
 5   cod_municipio                           5570 non-null   object
 6   municipio                               5570 non-null   object
 7   Ano (Código)                            5570 non-null   object
 8   Ano                                     5570 non-null   object
 9   Tipo de esgotamento sanitário (Código)  5570 non-null   object
 10  Tipo de esgotamento sanitário           5570 non-null   object
 11  Variável (Código)                       5570 non-null   object
 12  Variável                                5570 non-null   object
dtypes: float64(1), object(12)
memory usage: 565.8+ KB

None

In [15]:
dados_esgoto = dados_esgoto[['cod_municipio', 'municipio', 'total_domicilios_esgoto']]
display(dados_esgoto.head())

0 cod_municipio                   municipio  total_domicilios_esgoto
1       1100015  Alta Floresta D'Oeste - RO                     36.0
2       1100023              Ariquemes - RO                    693.0
3       1100031                 Cabixi - RO                     31.0
4       1100049                 Cacoal - RO                  21445.0
5       1100056             Cerejeiras - RO                   3406.0

In [ ]:
dados_consolidados = pd.merge(dados_consolidados, dados_esgoto, on=['cod_municipio', 'municipio'], how='left')
dados_consolidados['perc_esgoto_rede'] = (dados_consolidados['total_domicilios_esgoto'].div(dados_consolidados['total_domicilios'])) * 100
dados_consolidados = dados_consolidados.drop(columns=['total_domicilios_esgoto'])

display(dados_consolidados.head())

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836
1,1100023,Ariquemes - RO,34768,54.337322,1.993212
2,1100031,Cabixi - RO,1967,39.298424,1.576004
3,1100049,Cacoal - RO,31917,80.067049,67.189899
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211

In [17]:
import requests

response = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/6892/metadados")
metadados = response.json()
display(metadados['classificacoes'])

[{'id': 67,
  'nome': 'Destino do lixo',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 10972, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 2520, 'nome': 'Coletado', 'unidade': None, 'nivel': 1},
   {'id': 72120,
    'nome': 'Coletado no domicílio por serviço de limpeza',
    'unidade': None,
    'nivel': 2},
   {'id': 72121,
    'nome': 'Depositado em caçamba de serviço de limpeza',
    'unidade': None,
    'nivel': 2},
   {'id': 72122,
    'nome': 'Queimado na propriedade',
    'unidade': None,
    'nivel': 1},
   {'id': 72123,
    'nome': 'Enterrado na propriedade',
    'unidade': None,
    'nivel': 1},
   {'id': 72124,
    'nome': 'Jogado em terreno baldio, encosta ou área pública',
    'unidade': None,
    'nivel': 1},
   {'id': 1091, 'nome': 'Outro destino', 'unidade': None, 'nivel': 1}]}]

In [18]:
dados_lixo = sidrapy.get_table(
    table_code="6892",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022",
    classifications={"67": "2520"}
)

display(dados_lixo.head())
display(dados_lixo.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Destino do lixo (Código),Destino do lixo,Variável (Código),Variável
1,6,Município,1020,Unidades,4731,1100015,Alta Floresta D'Oeste - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
2,6,Município,1020,Unidades,31436,1100023,Ariquemes - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
3,6,Município,1020,Unidades,1201,1100031,Cabixi - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
4,6,Município,1020,Unidades,27339,1100049,Cacoal - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      5571 non-null   object
 1   NN      5571 non-null   object
 2   MC      5571 non-null   object
 3   MN      5571 non-null   object
 4   V       5571 non-null   object
 5   D1C     5571 non-null   object
 6   D1N     5571 non-null   object
 7   D2C     5571 non-null   object
 8   D2N     5571 non-null   object
 9   D3C     5571 non-null   object
 10  D3N     5571 non-null   object
 11  D4C     5571 non-null   object
 12  D4N     5571 non-null   object
dtypes: object(13)
memory usage: 565.9+ KB

None

In [19]:
dados_lixo.columns = dados_lixo.iloc[0]
dados_lixo = dados_lixo.iloc[1:]

display(dados_lixo.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Destino do lixo (Código),Destino do lixo,Variável (Código),Variável
1,6,Município,1020,Unidades,4731,1100015,Alta Floresta D'Oeste - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
2,6,Município,1020,Unidades,31436,1100023,Ariquemes - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
3,6,Município,1020,Unidades,1201,1100031,Cabixi - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
4,6,Município,1020,Unidades,27339,1100049,Cacoal - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados
5,6,Município,1020,Unidades,5112,1100056,Cerejeiras - RO,2022,2022,2520,Coletado,381,Domicílios particulares permanentes ocupados

In [20]:
dados_lixo = dados_lixo.rename(columns={'Município (Código)': 'cod_municipio', 'Município': 'municipio', 'Valor': 'total_domicilios_lixo'})
dados_lixo['total_domicilios_lixo'] = pd.to_numeric(dados_lixo['total_domicilios_lixo'], errors='coerce')

display(dados_lixo.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 1 to 5570
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nível Territorial (Código)  5570 non-null   object
 1   Nível Territorial           5570 non-null   object
 2   Unidade de Medida (Código)  5570 non-null   object
 3   Unidade de Medida           5570 non-null   object
 4   total_domicilios_lixo       5570 non-null   int64
 5   cod_municipio               5570 non-null   object
 6   municipio                   5570 non-null   object
 7   Ano (Código)                5570 non-null   object
 8   Ano                         5570 non-null   object
 9   Destino do lixo (Código)    5570 non-null   object
 10  Destino do lixo             5570 non-null   object
 11  Variável (Código)           5570 non-null   object
 12  Variável                    5570 non-null   object
dtypes: int64(1), object(12)
memory usage: 565.8+ KB

None

In [21]:
dados_lixo = dados_lixo[['cod_municipio', 'municipio', 'total_domicilios_lixo']]

display(dados_lixo.head())

0 cod_municipio                   municipio  total_domicilios_lixo
1       1100015  Alta Floresta D'Oeste - RO                   4731
2       1100023              Ariquemes - RO                  31436
3       1100031                 Cabixi - RO                   1201
4       1100049                 Cacoal - RO                  27339
5       1100056             Cerejeiras - RO                   5112

In [ ]:
dados_consolidados = pd.merge(dados_consolidados, dados_lixo, on=['cod_municipio', 'municipio'], how='left')
dados_consolidados['perc_lixo_coletado'] = (dados_consolidados['total_domicilios_lixo'].div(dados_consolidados['total_domicilios'])) * 100
dados_consolidados = dados_consolidados.drop(columns=['total_domicilios_lixo'])

display(dados_consolidados.head())

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397

In [23]:
import requests

response = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/9543/metadados")
metadados = response.json()
display(metadados['classificacoes'])

[{'id': 2,
  'nome': 'Sexo',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 6794, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 4, 'nome': 'Homens', 'unidade': None, 'nivel': 1},
   {'id': 5, 'nome': 'Mulheres', 'unidade': None, 'nivel': 1}]},
 {'id': 86,
  'nome': 'Cor ou raça',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 95251, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 2776, 'nome': 'Branca', 'unidade': None, 'nivel': 1},
   {'id': 2777, 'nome': 'Preta', 'unidade': None, 'nivel': 1},
   {'id': 2778, 'nome': 'Amarela', 'unidade': None, 'nivel': 1},
   {'id': 2779, 'nome': 'Parda', 'unidade': None, 'nivel': 1},
   {'id': 2780, 'nome': 'Indígena', 'unidade': None, 'nivel': 1}]},
 {'id': 287,
  'nome': 'Idade',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 100362, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 93086, 'nome': '15 a 19 anos', 'unidade': None, 'nivel': 1},
   {'id': 6572, 'nome': '15 anos', 'unidade': None, 'nivel': 2},
   {'id': 6573, 'nome': '16 anos', 'unidade': None, 'nivel': 2},
   {'id': 6574, 'nome': '17 anos', 'unidade': None, 'nivel': 2},
   {'id': 6575, 'nome': '18 anos', 'unidade': None, 'nivel': 2},
   {'id': 6576, 'nome': '19 anos', 'unidade': None, 'nivel': 2},
   {'id': 93087, 'nome': '20 a 24 anos', 'unidade': None, 'nivel': 1},
   {'id': 6577, 'nome': '20 anos', 'unidade': None, 'nivel': 2},
   {'id': 6578, 'nome': '21 anos', 'unidade': None, 'nivel': 2},
   {'id': 6579, 'nome': '22 anos', 'unidade': None, 'nivel': 2},
   {'id': 6580, 'nome': '23 anos', 'unidade': None, 'nivel': 2},
   {'id': 6581, 'nome': '24 anos', 'unidade': None, 'nivel': 2},
   {'id': 2999, 'nome': '25 a 34 anos', 'unidade': None, 'nivel': 1},
   {'id': 6582, 'nome': '25 anos', 'unidade': None, 'nivel': 2},
   {'id': 6656, 'nome': '26 anos', 'unidade': None, 'nivel': 2},
   {'id': 6657, 'nome': '27 anos', 'unidade': None, 'nivel': 2},
   {'id': 6658, 'nome': '28 anos', 'unidade': None, 'nivel': 2},
   {'id': 6659, 'nome': '29 anos', 'unidade': None, 'nivel': 2},
   {'id': 6583, 'nome': '30 anos', 'unidade': None, 'nivel': 2},
   {'id': 6584, 'nome': '31 anos', 'unidade': None, 'nivel': 2},
   {'id': 6585, 'nome': '32 anos', 'unidade': None, 'nivel': 2},
   {'id': 6586, 'nome': '33 anos', 'unidade': None, 'nivel': 2},
   {'id': 6587, 'nome': '34 anos', 'unidade': None, 'nivel': 2},
   {'id': 9482, 'nome': '35 a 44 anos', 'unidade': None, 'nivel': 1},
   {'id': 6588, 'nome': '35 anos', 'unidade': None, 'nivel': 2},
   {'id': 6589, 'nome': '36 anos', 'unidade': None, 'nivel': 2},
   {'id': 6590, 'nome': '37 anos', 'unidade': None, 'nivel': 2},
   {'id': 6591, 'nome': '38 anos', 'unidade': None, 'nivel': 2},
   {'id': 6592, 'nome': '39 anos', 'unidade': None, 'nivel': 2},
   {'id': 6593, 'nome': '40 anos', 'unidade': None, 'nivel': 2},
   {'id': 6594, 'nome': '41 anos', 'unidade': None, 'nivel': 2},
   {'id': 6595, 'nome': '42 anos', 'unidade': None, 'nivel': 2},
   {'id': 6596, 'nome': '43 anos', 'unidade': None, 'nivel': 2},
   {'id': 6597, 'nome': '44 anos', 'unidade': None, 'nivel': 2},
   {'id': 9483, 'nome': '45 a 54 anos', 'unidade': None, 'nivel': 1},
   {'id': 6598, 'nome': '45 anos', 'unidade': None, 'nivel': 2},
   {'id': 6599, 'nome': '46 anos', 'unidade': None, 'nivel': 2},
   {'id': 6600, 'nome': '47 anos', 'unidade': None, 'nivel': 2},
   {'id': 6601, 'nome': '48 anos', 'unidade': None, 'nivel': 2},
   {'id': 6602, 'nome': '49 anos', 'unidade': None, 'nivel': 2},
   {'id': 6603, 'nome': '50 anos', 'unidade': None, 'nivel': 2},
   {'id': 6604, 'nome': '51 anos', 'unidade': None, 'nivel': 2},
   {'id': 6605, 'nome': '52 anos', 'unidade': None, 'nivel': 2},
   {'id': 6606, 'nome': '53 anos', 'unidade': None, 'nivel': 2},
   {'id': 6607, 'nome': '54 anos', 'unidade': None, 'nivel': 2},
   {'id': 9484, 'nome': '55 a 64 anos', 'unidade': None, 'nivel': 1},
   {'id': 6608, 'nome': '55 anos', 'unidade': None, 'nivel': 2},
   {'id': 6609, 'nome': '56 anos', 'unidade': None, 'nivel': 2},
   {'id': 6610, 'nome': '57 anos', 'unidade': None, 'nivel': 2},
   {'id': 6611, 'nome': '58 anos', 'unidade': None, 'nivel': 2},
   {'id': 6612, 'nome': '59 anos', 'unidade': None, 'nivel': 2},
   {'id': 6613, 'nome': '60 anos', 'unidade': None, 'nivel': 2},
   {'id': 6614, 'nome': '61 anos', 'unidade': None, 'nivel': 2},
   {'id': 6615, 'nome': '62 anos', 'unidade': None, 'nivel': 2},
   {'id': 6616, 'nome': '63 anos', 'unidade': None, 'nivel': 2},
   {'id': 6617, 'nome': '64 anos', 'unidade': None, 'nivel': 2},
   {'id': 3000, 'nome': '65 anos ou mais', 'unidade': None, 'nivel': 1},
   {'id': 9486, 'nome': '75 anos ou mais', 'unidade': None, 'nivel': 2},
   {'id': 113623, 'nome': '80 anos ou mais', 'unidade': None, 'nivel': 3}]}]

In [24]:
dados_alfabetizacao = sidrapy.get_table(
    table_code="9543",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022",
    classifications={"2": "6794"}
)

display(dados_alfabetizacao.head())
display(dados_alfabetizacao.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N,D5C,D5N,D6C,D6N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Sexo (Código),Sexo,Variável (Código),Variável,Cor ou raça (Código),Cor ou raça,Idade (Código),Idade
1,6,Município,2,%,91.59,1100015,Alta Floresta D'Oeste - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
2,6,Município,2,%,94.08,1100023,Ariquemes - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
3,6,Município,2,%,89.82,1100031,Cabixi - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
4,6,Município,2,%,93.71,1100049,Cacoal - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      5571 non-null   object
 1   NN      5571 non-null   object
 2   MC      5571 non-null   object
 3   MN      5571 non-null   object
 4   V       5571 non-null   object
 5   D1C     5571 non-null   object
 6   D1N     5571 non-null   object
 7   D2C     5571 non-null   object
 8   D2N     5571 non-null   object
 9   D3C     5571 non-null   object
 10  D3N     5571 non-null   object
 11  D4C     5571 non-null   object
 12  D4N     5571 non-null   object
 13  D5C     5571 non-null   object
 14  D5N     5571 non-null   object
 15  D6C     5571 non-null   object
 16  D6N     5571 non-null   object
dtypes: object(17)
memory usage: 740.0+ KB

None

In [25]:
dados_alfabetizacao.columns = dados_alfabetizacao.iloc[0]
dados_alfabetizacao = dados_alfabetizacao.iloc[1:]

display(dados_alfabetizacao.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Sexo (Código),Sexo,Variável (Código),Variável,Cor ou raça (Código),Cor ou raça,Idade (Código),Idade
1,6,Município,2,%,91.59,1100015,Alta Floresta D'Oeste - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
2,6,Município,2,%,94.08,1100023,Ariquemes - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
3,6,Município,2,%,89.82,1100031,Cabixi - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
4,6,Município,2,%,93.71,1100049,Cacoal - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total
5,6,Município,2,%,92.15,1100056,Cerejeiras - RO,2022,2022,6794,Total,2513,Taxa de alfabetização das pessoas de 15 anos o...,95251,Total,100362,Total

In [26]:
dados_alfabetizacao = dados_alfabetizacao.rename(columns={'Município (Código)': 'cod_municipio', 'Município': 'municipio', 'Valor': 'perc_alfabetizacao'})
dados_alfabetizacao['perc_alfabetizacao'] = pd.to_numeric(dados_alfabetizacao['perc_alfabetizacao'], errors='coerce')

display(dados_alfabetizacao.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 1 to 5570
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nível Territorial (Código)  5570 non-null   object
 1   Nível Territorial           5570 non-null   object
 2   Unidade de Medida (Código)  5570 non-null   object
 3   Unidade de Medida           5570 non-null   object
 4   perc_alfabetizacao          5570 non-null   float64
 5   cod_municipio               5570 non-null   object
 6   municipio                   5570 non-null   object
 7   Ano (Código)                5570 non-null   object
 8   Ano                         5570 non-null   object
 9   Sexo (Código)               5570 non-null   object
 10  Sexo                        5570 non-null   object
 11  Variável (Código)           5570 non-null   object
 12  Variável                    5570 non-null   object
 13  Cor ou raça (Código)        5570 non-null   object
 14  Cor ou raça                 5570 non-null   object
 15  Idade (Código)              5570 non-null   object
 16  Idade                       5570 non-null   object
dtypes: float64(1), object(16)
memory usage: 739.9+ KB

None

In [27]:
dados_alfabetizacao = dados_alfabetizacao[['cod_municipio', 'municipio', 'perc_alfabetizacao']]

display(dados_alfabetizacao.head())

0 cod_municipio                   municipio  perc_alfabetizacao
1       1100015  Alta Floresta D'Oeste - RO               91.59
2       1100023              Ariquemes - RO               94.08
3       1100031                 Cabixi - RO               89.82
4       1100049                 Cacoal - RO               93.71
5       1100056             Cerejeiras - RO               92.15

In [28]:
dados_consolidados = pd.merge(dados_consolidados, dados_alfabetizacao, on=['cod_municipio', 'municipio'], how='left')

display(dados_consolidados.head())

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado,perc_alfabetizacao
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481,91.59
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475,94.08
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448,89.82
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547,93.71
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397,92.15

In [29]:
import requests

response = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/10295/metadados")
metadados = response.json()
display(metadados['classificacoes'])

[{'id': 2,
  'nome': 'Sexo',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 6794, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 4, 'nome': 'Homens', 'unidade': None, 'nivel': 1},
   {'id': 5, 'nome': 'Mulheres', 'unidade': None, 'nivel': 1}]},
 {'id': 86,
  'nome': 'Cor ou raça',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 95251, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 2776, 'nome': 'Branca', 'unidade': None, 'nivel': 1},
   {'id': 2777, 'nome': 'Preta', 'unidade': None, 'nivel': 1},
   {'id': 2778, 'nome': 'Amarela', 'unidade': None, 'nivel': 1},
   {'id': 2779, 'nome': 'Parda', 'unidade': None, 'nivel': 1},
   {'id': 2780, 'nome': 'Indígena', 'unidade': None, 'nivel': 1}]},
 {'id': 58,
  'nome': 'Grupo de idade',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 95253, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 33269, 'nome': '0 a 17 anos', 'unidade': None, 'nivel': 1},
   {'id': 6744, 'nome': '0 a 9 anos', 'unidade': None, 'nivel': 2},
   {'id': 118282, 'nome': '10 a 13 anos', 'unidade': None, 'nivel': 2},
   {'id': 114535, 'nome': '14 a 17 anos', 'unidade': None, 'nivel': 2},
   {'id': 100052, 'nome': '18 a 24 anos', 'unidade': None, 'nivel': 1},
   {'id': 2793, 'nome': '18 a 19 anos', 'unidade': None, 'nivel': 2},
   {'id': 1144, 'nome': '20 a 24 anos', 'unidade': None, 'nivel': 2},
   {'id': 108866, 'nome': '25 anos ou mais', 'unidade': None, 'nivel': 1},
   {'id': 100754, 'nome': '25 a 64 anos', 'unidade': None, 'nivel': 2},
   {'id': 1145, 'nome': '25 a 29 anos', 'unidade': None, 'nivel': 3},
   {'id': 1146, 'nome': '30 a 34 anos', 'unidade': None, 'nivel': 3},
   {'id': 1147, 'nome': '35 a 39 anos', 'unidade': None, 'nivel': 3},
   {'id': 1148, 'nome': '40 a 44 anos', 'unidade': None, 'nivel': 3},
   {'id': 1149, 'nome': '45 a 49 anos', 'unidade': None, 'nivel': 3},
   {'id': 1150, 'nome': '50 a 54 anos', 'unidade': None, 'nivel': 3},
   {'id': 1151, 'nome': '55 a 59 anos', 'unidade': None, 'nivel': 3},
   {'id': 1152, 'nome': '60 a 64 anos', 'unidade': None, 'nivel': 3},
   {'id': 6798, 'nome': '65 anos ou mais', 'unidade': None, 'nivel': 2},
   {'id': 1153, 'nome': '65 a 69 anos', 'unidade': None, 'nivel': 3},
   {'id': 1154, 'nome': '70 a 74 anos', 'unidade': None, 'nivel': 3},
   {'id': 1155, 'nome': '75 a 79 anos', 'unidade': None, 'nivel': 3},
   {'id': 2503, 'nome': '80 anos ou mais', 'unidade': None, 'nivel': 3}]}]

In [30]:
dados_renda = sidrapy.get_table(
    table_code="10295",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022",
    classifications={"2": "6794"}
)

display(dados_renda.head())
display(dados_renda.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N,D5C,D5N,D6C,D6N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Sexo (Código),Sexo,Variável (Código),Variável,Grupo de idade (Código),Grupo de idade,Cor ou raça (Código),Cor ou raça
1,6,Município,45,Pessoas,21447,1100015,Alta Floresta D'Oeste - RO,2022,2022,6794,Total,13604,Moradores em domicílios particulares permanent...,95253,Total,95251,Total
2,6,Município,38,Reais,1210.60,1100015,Alta Floresta D'Oeste - RO,2022,2022,6794,Total,13431,Valor do rendimento nominal médio mensal domic...,95253,Total,95251,Total
3,6,Município,38,Reais,920.00,1100015,Alta Floresta D'Oeste - RO,2022,2022,6794,Total,13534,Valor do rendimento nominal mediano mensal dom...,95253,Total,95251,Total
4,6,Município,45,Pessoas,96129,1100023,Ariquemes - RO,2022,2022,6794,Total,13604,Moradores em domicílios particulares permanent...,95253,Total,95251,Total

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16711 entries, 0 to 16710
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      16711 non-null  object
 1   NN      16711 non-null  object
 2   MC      16711 non-null  object
 3   MN      16711 non-null  object
 4   V       16711 non-null  object
 5   D1C     16711 non-null  object
 6   D1N     16711 non-null  object
 7   D2C     16711 non-null  object
 8   D2N     16711 non-null  object
 9   D3C     16711 non-null  object
 10  D3N     16711 non-null  object
 11  D4C     16711 non-null  object
 12  D4N     16711 non-null  object
 13  D5C     16711 non-null  object
 14  D5N     16711 non-null  object
 15  D6C     16711 non-null  object
 16  D6N     16711 non-null  object
dtypes: object(17)
memory usage: 2.2+ MB

None

In [31]:
dados_renda.columns = dados_renda.iloc[0]
dados_renda = dados_renda.iloc[1:]

dados_renda = dados_renda[dados_renda['Variável (Código)'] == '13431']

display(dados_renda.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Sexo (Código),Sexo,Variável (Código),Variável,Grupo de idade (Código),Grupo de idade,Cor ou raça (Código),Cor ou raça
2,6,Município,38,Reais,1210.60,1100015,Alta Floresta D'Oeste - RO,2022,2022,6794,Total,13431,Valor do rendimento nominal médio mensal domic...,95253,Total,95251,Total
5,6,Município,38,Reais,1458.57,1100023,Ariquemes - RO,2022,2022,6794,Total,13431,Valor do rendimento nominal médio mensal domic...,95253,Total,95251,Total
8,6,Município,38,Reais,1323.79,1100031,Cabixi - RO,2022,2022,6794,Total,13431,Valor do rendimento nominal médio mensal domic...,95253,Total,95251,Total
11,6,Município,38,Reais,1625.88,1100049,Cacoal - RO,2022,2022,6794,Total,13431,Valor do rendimento nominal médio mensal domic...,95253,Total,95251,Total
14,6,Município,38,Reais,1554.33,1100056,Cerejeiras - RO,2022,2022,6794,Total,13431,Valor do rendimento nominal médio mensal domic...,95253,Total,95251,Total

In [32]:
dados_renda = dados_renda.rename(columns={'Município (Código)': 'cod_municipio', 'Município': 'municipio', 'Valor': 'renda_media'})
dados_renda['renda_media'] = pd.to_numeric(dados_renda['renda_media'], errors='coerce')

display(dados_renda.info())

<class 'pandas.core.frame.DataFrame'>
Index: 5570 entries, 2 to 16709
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nível Territorial (Código)  5570 non-null   object
 1   Nível Territorial           5570 non-null   object
 2   Unidade de Medida (Código)  5570 non-null   object
 3   Unidade de Medida           5570 non-null   object
 4   renda_media                 5570 non-null   float64
 5   cod_municipio               5570 non-null   object
 6   municipio                   5570 non-null   object
 7   Ano (Código)                5570 non-null   object
 8   Ano                         5570 non-null   object
 9   Sexo (Código)               5570 non-null   object
 10  Sexo                        5570 non-null   object
 11  Variável (Código)           5570 non-null   object
 12  Variável                    5570 non-null   object
 13  Grupo de idade (Código)     5570 non-null   object
 14  Grupo de idade              5570 non-null   object
 15  Cor ou raça (Código)        5570 non-null   object
 16  Cor ou raça                 5570 non-null   object
dtypes: float64(1), object(16)
memory usage: 783.3+ KB

None

In [33]:
dados_renda = dados_renda[['cod_municipio', 'municipio', 'renda_media']]

display(dados_renda.head())

0  cod_municipio                   municipio  renda_media
2        1100015  Alta Floresta D'Oeste - RO      1210.60
5        1100023              Ariquemes - RO      1458.57
8        1100031                 Cabixi - RO      1323.79
11       1100049                 Cacoal - RO      1625.88
14       1100056             Cerejeiras - RO      1554.33

In [34]:
dados_consolidados = pd.merge(dados_consolidados, dados_renda, on=['cod_municipio', 'municipio'], how='left')

display(dados_consolidados.head())

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado,perc_alfabetizacao,renda_media
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481,91.59,1210.60
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475,94.08,1458.57
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448,89.82,1323.79
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547,93.71,1625.88
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397,92.15,1554.33

In [35]:
import requests

response = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados/9923/metadados")
metadados = response.json()
display(metadados['classificacoes'])

[{'id': 1,
  'nome': 'Situação do domicílio',
  'sumarizacao': {'status': True, 'excecao': []},
  'categorias': [{'id': 6795, 'nome': 'Total', 'unidade': None, 'nivel': 0},
   {'id': 1, 'nome': 'Urbana', 'unidade': None, 'nivel': 1},
   {'id': 2, 'nome': 'Rural', 'unidade': None, 'nivel': 1}]}]

In [36]:
dados_domicilios = sidrapy.get_table(
    table_code="9923",
    territorial_level="6",
    ibge_territorial_code="all",
    period="2022",
    classifications={"1": "all"}
)

display(dados_domicilios.head())
display(dados_domicilios.info())

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Situação do domicílio (Código),Situação do domicílio,Variável (Código),Variável
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste - RO,2022,2022,6795,Total,93,População residente
2,6,Município,45,Pessoas,12971,1100015,Alta Floresta D'Oeste - RO,2022,2022,1,Urbana,93,População residente
3,6,Município,45,Pessoas,8523,1100015,Alta Floresta D'Oeste - RO,2022,2022,2,Rural,93,População residente
4,6,Município,45,Pessoas,96833,1100023,Ariquemes - RO,2022,2022,6795,Total,93,População residente

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16711 entries, 0 to 16710
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      16711 non-null  object
 1   NN      16711 non-null  object
 2   MC      16711 non-null  object
 3   MN      16711 non-null  object
 4   V       16711 non-null  object
 5   D1C     16711 non-null  object
 6   D1N     16711 non-null  object
 7   D2C     16711 non-null  object
 8   D2N     16711 non-null  object
 9   D3C     16711 non-null  object
 10  D3N     16711 non-null  object
 11  D4C     16711 non-null  object
 12  D4N     16711 non-null  object
dtypes: object(13)
memory usage: 1.7+ MB

None

In [37]:
dados_domicilios.columns = dados_domicilios.iloc[0]
dados_domicilios = dados_domicilios[1:]

dados_domicilios = dados_domicilios[dados_domicilios['Situação do domicílio (Código)'] != '2']

display(dados_domicilios.head())

,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Situação do domicílio (Código),Situação do domicílio,Variável (Código),Variável
1,6,Município,45,Pessoas,21494,1100015,Alta Floresta D'Oeste - RO,2022,2022,6795,Total,93,População residente
2,6,Município,45,Pessoas,12971,1100015,Alta Floresta D'Oeste - RO,2022,2022,1,Urbana,93,População residente
4,6,Município,45,Pessoas,96833,1100023,Ariquemes - RO,2022,2022,6795,Total,93,População residente
5,6,Município,45,Pessoas,83952,1100023,Ariquemes - RO,2022,2022,1,Urbana,93,População residente
7,6,Município,45,Pessoas,5351,1100031,Cabixi - RO,2022,2022,6795,Total,93,População residente

In [38]:
dom_total = dados_domicilios[dados_domicilios['Situação do domicílio (Código)'] == '6795'][['Município (Código)','Valor']]
dom_urb = dados_domicilios[dados_domicilios['Situação do domicílio (Código)'] == '1'][['Município (Código)','Valor']]

dom = pd.merge(dom_urb, dom_total, on='Município (Código)', how='left')

display(dom.head())

0 Município (Código) Valor_x Valor_y
0            1100015   12971   21494
1            1100023   83952   96833
2            1100031    2846    5351
3            1100049   71907   86887
4            1100056   14116   15890

In [39]:
dom['Valor_x'] = pd.to_numeric(dom['Valor_x'], errors='coerce')
dom['Valor_y'] = pd.to_numeric(dom['Valor_y'], errors='coerce')

dom['per_domicilio_urbano'] = (dom['Valor_x'].div(dom['Valor_y'])) * 100

dom = dom.drop(columns=['Valor_x', 'Valor_y'])

display(dom.head())

0 Município (Código)  per_domicilio_urbano
0            1100015             60.347074
1            1100023             86.697717
2            1100031             53.186320
3            1100049             82.759216
4            1100056             88.835746

In [40]:
dom = dom.rename(columns={'Município (Código)': 'cod_municipio'})

dados_consolidados = pd.merge(dados_consolidados, dom, on='cod_municipio', how='left')

display(dados_consolidados.head())

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado,perc_alfabetizacao,renda_media,per_domicilio_urbano
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481,91.59,1210.60,60.347074
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475,94.08,1458.57,86.697717
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448,89.82,1323.79,53.186320
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547,93.71,1625.88,82.759216
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397,92.15,1554.33,88.835746

In [41]:
dados_consolidados.to_csv(caminho / 'processados' / 'sidra_consolidado.csv', index=False)

Fim!