Notícia da Emancipação/Criação dos novos municípios brasileiros - 5565 --> 5570

https://oglobo.globo.com/politica/com-5-novos-municipios-brasil-agora-tem-5570-cidades-7235803#:~:text=Com%205%20novos%20munic%C3%ADpios%2C%20Brasil%20agora%20tem%205.570%20cidades.

In [29]:
import pandas as pd
from pathlib import Path

caminho = Path(r"C:\Users\Felipe\Documents\Python\Clusterizacao_Municipios\dados")

atlas = pd.read_csv(caminho / 'processados' / 'Atlas_tratado.csv')
sidra = pd.read_csv(caminho / 'processados' / 'sidra_consolidado.csv')

display(atlas.head(10))
display(sidra.head(10))
display(atlas.info())
display(sidra.info())

,municipio,IDHM,IDHM Renda,IDHM Educação,IDHM Longevidade,municipio_sidra
0,São Caetano do Sul (SP),0.862,0.891,0.811,0.887,São Caetano do Sul - SP
1,Águas de São Pedro (SP),0.854,0.849,0.825,0.890,Águas de São Pedro - SP
2,Florianópolis (SC),0.847,0.870,0.800,0.873,Florianópolis - SC
3,Vitória (ES),0.845,0.876,0.805,0.855,Vitória - ES
4,Balneário Camboriú (SC),0.845,0.854,0.789,0.894,Balneário Camboriú - SC
5,Santos (SP),0.840,0.861,0.807,0.852,Santos - SP
6,Niterói (RJ),0.837,0.887,0.773,0.854,Niterói - RJ
7,Joaçaba (SC),0.827,0.823,0.771,0.891,Joaçaba - SC
8,Brasília (DF),0.824,0.863,0.742,0.873,Brasília - DF
9,Curitiba (PR),0.823,0.850,0.768,0.855,Curitiba - PR

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado,perc_alfabetizacao,renda_media,per_domicilio_urbano
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481,91.59,1210.60,60.347074
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475,94.08,1458.57,86.697717
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448,89.82,1323.79,53.186320
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547,93.71,1625.88,82.759216
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397,92.15,1554.33,88.835746
5,1100064,Colorado do Oeste - RO,5991,70.806209,2.620598,77.249207,90.47,1666.54,74.755794
6,1100072,Corumbiara - RO,2840,20.985915,0.704225,47.887324,91.52,1234.62,36.973002
7,1100080,Costa Marques - RO,4161,19.346311,0.048065,63.566450,92.92,1088.06,52.823315
8,1100098,Espigão D'Oeste - RO,10470,44.871060,6.599809,74.288443,92.01,1371.66,72.931257
9,1100106,Guajará-Mirim - RO,11803,40.464289,9.014657,78.141151,94.16,1035.94,80.577348

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   municipio         5565 non-null   object
 1   IDHM              5565 non-null   float64
 2   IDHM Renda        5565 non-null   float64
 3   IDHM Educação     5565 non-null   float64
 4   IDHM Longevidade  5565 non-null   float64
 5   municipio_sidra   5565 non-null   object
dtypes: float64(4), object(2)
memory usage: 261.0+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cod_municipio         5570 non-null   int64
 1   municipio             5570 non-null   object
 2   total_domicilios      5570 non-null   int64
 3   perc_agua_rede        5562 non-null   float64
 4   perc_esgoto_rede      5545 non-null   float64
 5   perc_lixo_coletado    5570 non-null   float64
 6   perc_alfabetizacao    5570 non-null   float64
 7   renda_media           5570 non-null   float64
 8   per_domicilio_urbano  5570 non-null   float64
dtypes: float64(6), int64(2), object(1)
memory usage: 391.8+ KB

None

In [30]:
sidra_nomes = set(sidra['municipio'])
atlas_nomes = set(atlas['municipio_sidra'])

print(f'Municípios na Base do Atlas: {len(atlas_nomes)}')
print(f'Municípios na Base do Sidra: {len(sidra_nomes)}\n')

apenas_sidra = sidra_nomes - atlas_nomes
print(f"Municípios no SIDRA sem correspondência no Atlas: {len(apenas_sidra)}")
print(sorted(apenas_sidra))

Municípios na Base do Atlas: 5565
Municípios na Base do Sidra: 5570

Municípios no SIDRA sem correspondência no Atlas: 79
['Abreu e Lima - PE', 'Amparo do São Francisco - SE', "Aparecida d'Oeste - SP", 'Araçás - BA', 'Atílio Vivácqua - ES', 'Balneário Rincão - SC', 'Barão do Monte Alto - MG', 'Biritiba Mirim - SP', 'Brazópolis - MG', 'Campo Grande - RN', "Dias d'Ávila - BA", 'Dona Euzébia - MG', 'Eldorado do Carajás - PA', 'Embu das Artes - SP', 'Ereré - CE', "Estrela d'Oeste - SP", 'Florínea - SP', 'Graccho Cardoso - SE', 'Grão-Pará - SC', "Guarani d'Oeste - SP", "Herval d'Oeste - SC", 'Iguaracy - PE', 'Itaoca - SP', 'Itapajé - CE', "Itapejara d'Oeste - PR", "Itaporanga d'Ajuda - SE", 'Iuiu - BA', 'Joca Claudino - PB', "Lagoa d'Anta - RN", 'Lauro Müller - SC', "Mirassol d'Oeste - MT", 'Mojuí dos Campos - PA', 'Muquém do São Francisco - BA', "Mãe d'Água - PB", "Olho d'Água - PB", "Olho d'Água Grande - AL", "Olho d'Água das Cunhãs - MA", "Olho d'Água das Flores - AL", "Olho d'Água do Borges - RN", "Olho d'Água do Casado - AL", "Olhos-d'Água - MG", "Palmeira d'Oeste - SP", 'Paraíso das Águas - MS', 'Passa Vinte - MG', 'Passa e Fica - RN', 'Pedro II - PI', 'Pescaria Brava - SC', "Pingo-d'Água - MG", 'Pinto Bandeira - RS', 'Pio IX - PI', 'Pio XII - MA', 'Pontes e Lacerda - MT', 'Poxoréu - MT', "Pérola d'Oeste - PR", 'Quixaba - PB', 'Restinga Sêca - RS', "Santa Bárbara d'Oeste - SP", "Santa Clara d'Oeste - SP", 'Santa Izabel do Pará - PA', "Santa Rita d'Oeste - SP", 'Santa Terezinha - BA', 'Santo Antônio de Leverger - MT', 'Serra Caiada - RN', 'São Cristóvão do Sul - SC', "São Jorge d'Oeste - PR", "São João d'Aliança - GO", 'São João del Rei - MG', "São João do Pau d'Alho - SP", 'São Luiz do Norte - GO', 'São Luiz do Paraitinga - SP', 'São Tomé das Letras - MG', 'São Vicente Férrer - PE', 'São Vicente do Seridó - PB', "Sítio d'Abadia - GO", 'Tabocão - TO', "Tanque d'Arca - AL", 'Vespasiano Corrêa - RS', 'Westfália - RS', 'Xangri-lá - RS']

In [31]:
apenas_atlas = atlas_nomes - sidra_nomes
print(f"Municípios no Atlas sem correspondência no SIDRA: {len(apenas_atlas)}")
print(sorted(apenas_atlas))

Municípios no Atlas sem correspondência no SIDRA: 74
['Abreu E Lima - PE', 'Amparo de São Francisco - SE', "Aparecida D'Oeste - SP", 'Araças - BA', 'Atilio Vivacqua - ES', 'Augusto Severo - RN', 'Barão de Monte Alto - MG', 'Biritiba-Mirim - SP', 'Brasópolis - MG', "Dias D'Ávila - BA", 'Dona Eusébia - MG', 'Eldorado dos Carajás - PA', 'Embu - SP', 'Ererê - CE', "Estrela D'Oeste - SP", 'Florínia - SP', 'Fortaleza do Tabocão - TO', 'Gracho Cardoso - SE', 'Grão Pará - SC', "Guarani D'Oeste - SP", "Herval D'Oeste - SC", 'Iguaraci - PE', 'Itapagé - CE', "Itapejara D'Oeste - PR", "Itaporanga D'Ajuda - SE", 'Itaóca - SP', 'Iuiú - BA', "Lagoa D'Anta - RN", 'Lauro Muller - SC', "Mirassol D'Oeste - MT", 'Muquém de São Francisco - BA', "Mãe D'Água - PB", "Olho D'Água - PB", "Olho D'Água Grande - AL", "Olho D'Água das Cunhãs - MA", "Olho D'Água das Flores - AL", "Olho D'Água do Casado - AL", "Olho-D'Água do Borges - RN", "Olhos-D'Água - MG", "Palmeira D'Oeste - SP", 'Passa E Fica - RN', 'Passa-Vinte - MG', 'Pedro Ii - PI', "Pingo-D'Água - MG", 'Pio Ix - PI', 'Pio Xii - MA', 'Pontes E Lacerda - MT', 'Poxoréo - MT', 'Presidente Juscelino - RN', "Pérola D'Oeste - PR", 'Quixabá - PB', 'Restinga Seca - RS', "Santa Bárbara D'Oeste - SP", "Santa Clara D'Oeste - SP", 'Santa Isabel do Pará - PA', "Santa Rita D'Oeste - SP", 'Santa Teresinha - BA', 'Santarém - PB', 'Santo Antônio do Leverger - MT', 'Seridó - PB', 'São Cristovão do Sul - SC', "São Jorge D'Oeste - PR", "São João D'Aliança - GO", 'São João Del Rei - MG', "São João do Pau D'Alho - SP", 'São Luís do Paraitinga - SP', 'São Luíz do Norte - GO', 'São Thomé das Letras - MG', 'São Vicente Ferrer - PE', "Sítio D'Abadia - GO", "Tanque D'Arca - AL", 'Vespasiano Correa - RS', 'Westfalia - RS', 'Xangri-Lá - RS']

In [32]:
atlas['municipio_sidra_lower'] = atlas['municipio_sidra'].str.lower()
sidra['municipio_lower'] = sidra['municipio'].str.lower()

apenas_sidra_lower = set(sidra['municipio_lower']) - set(atlas['municipio_sidra_lower'])
print(f"Sem correspondência após lowercase: {len(apenas_sidra_lower)}\n")
print(sorted(apenas_sidra_lower))

Sem correspondência após lowercase: 44

['amparo do são francisco - se', 'araçás - ba', 'atílio vivácqua - es', 'balneário rincão - sc', 'barão do monte alto - mg', 'biritiba mirim - sp', 'brazópolis - mg', 'campo grande - rn', 'dona euzébia - mg', 'eldorado do carajás - pa', 'embu das artes - sp', 'ereré - ce', 'florínea - sp', 'graccho cardoso - se', 'grão-pará - sc', 'iguaracy - pe', 'itaoca - sp', 'itapajé - ce', 'iuiu - ba', 'joca claudino - pb', 'lauro müller - sc', 'mojuí dos campos - pa', 'muquém do são francisco - ba', "olho d'água do borges - rn", 'paraíso das águas - ms', 'passa vinte - mg', 'pescaria brava - sc', 'pinto bandeira - rs', 'poxoréu - mt', 'quixaba - pb', 'restinga sêca - rs', 'santa izabel do pará - pa', 'santa terezinha - ba', 'santo antônio de leverger - mt', 'serra caiada - rn', 'são cristóvão do sul - sc', 'são luiz do norte - go', 'são luiz do paraitinga - sp', 'são tomé das letras - mg', 'são vicente do seridó - pb', 'são vicente férrer - pe', 'tabocão - to', 'vespasiano corrêa - rs', 'westfália - rs']

In [33]:
apenas_atlas_lower = set(atlas['municipio_sidra_lower']) - set(sidra['municipio_lower'])
print(f"Sem correspondência após lowercase: {len(apenas_atlas_lower)}\n")
print(sorted(apenas_atlas_lower))

Sem correspondência após lowercase: 39

['amparo de são francisco - se', 'araças - ba', 'atilio vivacqua - es', 'augusto severo - rn', 'barão de monte alto - mg', 'biritiba-mirim - sp', 'brasópolis - mg', 'dona eusébia - mg', 'eldorado dos carajás - pa', 'embu - sp', 'ererê - ce', 'florínia - sp', 'fortaleza do tabocão - to', 'gracho cardoso - se', 'grão pará - sc', 'iguaraci - pe', 'itapagé - ce', 'itaóca - sp', 'iuiú - ba', 'lauro muller - sc', 'muquém de são francisco - ba', "olho-d'água do borges - rn", 'passa-vinte - mg', 'poxoréo - mt', 'presidente juscelino - rn', 'quixabá - pb', 'restinga seca - rs', 'santa isabel do pará - pa', 'santa teresinha - ba', 'santarém - pb', 'santo antônio do leverger - mt', 'seridó - pb', 'são cristovão do sul - sc', 'são luís do paraitinga - sp', 'são luíz do norte - go', 'são thomé das letras - mg', 'são vicente ferrer - pe', 'vespasiano correa - rs', 'westfalia - rs']

In [34]:
correcoes = {
    'amparo de são francisco - se': 'amparo do são francisco - se',
    'araças - ba': 'araçás - ba',
    'atilio vivacqua - es': 'atílio vivácqua - es',
    'augusto severo - rn': 'campo grande - rn',
    'barão de monte alto - mg': 'barão do monte alto - mg',
    'biritiba-mirim - sp': 'biritiba mirim - sp',
    'brasópolis - mg': 'brazópolis - mg',
    'dona eusébia - mg': 'dona euzébia - mg',
    'eldorado dos carajás - pa': 'eldorado do carajás - pa',
    'embu - sp': 'embu das artes - sp',
    'ererê - ce': 'ereré - ce',
    'florínia - sp': 'florínea - sp',
    'fortaleza do tabocão - to': 'tabocão - to',
    'gracho cardoso - se': 'graccho cardoso - se',
    'grão pará - sc': 'grão-pará - sc',
    'iguaraci - pe': 'iguaracy - pe',
    'itapagé - ce': 'itapajé - ce',
    'itaóca - sp': 'itaoca - sp',
    'iuiú - ba': 'iuiu - ba',
    'lauro muller - sc': 'lauro müller - sc',
    'muquém de são francisco - ba': 'muquém do são francisco - ba',
    "olho-d'água do borges - rn": "olho d'água do borges - rn",
    'passa-vinte - mg': 'passa vinte - mg',
    'poxoréo - mt': 'poxoréu - mt',
    'presidente juscelino - rn': 'serra caiada - rn',
    'quixabá - pb': 'quixaba - pb',
    'restinga seca - rs': 'restinga sêca - rs',
    'santa isabel do pará - pa': 'santa izabel do pará - pa',
    'santa teresinha - ba': 'santa terezinha - ba',
    'santarém - pb': 'joca claudino - pb',
    'santo antônio do leverger - mt': 'santo antônio de leverger - mt',
    'seridó - pb': 'são vicente do seridó - pb',
    'são cristovão do sul - sc': 'são cristóvão do sul - sc',
    'são luís do paraitinga - sp': 'são luiz do paraitinga - sp',
    'são luíz do norte - go': 'são luiz do norte - go',
    'são thomé das letras - mg': 'são tomé das letras - mg',
    'são vicente ferrer - pe': 'são vicente férrer - pe',
    'vespasiano correa - rs': 'vespasiano corrêa - rs',
    'westfalia - rs': 'westfália - rs',
}

atlas['municipio_sidra_lower'] = atlas['municipio_sidra_lower'].replace(correcoes)

In [35]:
so_no_sidra_lower = set(sidra['municipio_lower']) - set(atlas['municipio_sidra_lower'])
print(f"Sem correspondência após correções: {len(so_no_sidra_lower)}")
print(sorted(so_no_sidra_lower))

Sem correspondência após correções: 5
['balneário rincão - sc', 'mojuí dos campos - pa', 'paraíso das águas - ms', 'pescaria brava - sc', 'pinto bandeira - rs']

In [36]:
display(sidra.head(10))
display(atlas.head(10))

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado,perc_alfabetizacao,renda_media,per_domicilio_urbano,municipio_lower
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481,91.59,1210.60,60.347074,alta floresta d'oeste - ro
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475,94.08,1458.57,86.697717,ariquemes - ro
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448,89.82,1323.79,53.186320,cabixi - ro
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547,93.71,1625.88,82.759216,cacoal - ro
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397,92.15,1554.33,88.835746,cerejeiras - ro
5,1100064,Colorado do Oeste - RO,5991,70.806209,2.620598,77.249207,90.47,1666.54,74.755794,colorado do oeste - ro
6,1100072,Corumbiara - RO,2840,20.985915,0.704225,47.887324,91.52,1234.62,36.973002,corumbiara - ro
7,1100080,Costa Marques - RO,4161,19.346311,0.048065,63.566450,92.92,1088.06,52.823315,costa marques - ro
8,1100098,Espigão D'Oeste - RO,10470,44.871060,6.599809,74.288443,92.01,1371.66,72.931257,espigão d'oeste - ro
9,1100106,Guajará-Mirim - RO,11803,40.464289,9.014657,78.141151,94.16,1035.94,80.577348,guajará-mirim - ro

,municipio,IDHM,IDHM Renda,IDHM Educação,IDHM Longevidade,municipio_sidra,municipio_sidra_lower
0,São Caetano do Sul (SP),0.862,0.891,0.811,0.887,São Caetano do Sul - SP,são caetano do sul - sp
1,Águas de São Pedro (SP),0.854,0.849,0.825,0.890,Águas de São Pedro - SP,águas de são pedro - sp
2,Florianópolis (SC),0.847,0.870,0.800,0.873,Florianópolis - SC,florianópolis - sc
3,Vitória (ES),0.845,0.876,0.805,0.855,Vitória - ES,vitória - es
4,Balneário Camboriú (SC),0.845,0.854,0.789,0.894,Balneário Camboriú - SC,balneário camboriú - sc
5,Santos (SP),0.840,0.861,0.807,0.852,Santos - SP,santos - sp
6,Niterói (RJ),0.837,0.887,0.773,0.854,Niterói - RJ,niterói - rj
7,Joaçaba (SC),0.827,0.823,0.771,0.891,Joaçaba - SC,joaçaba - sc
8,Brasília (DF),0.824,0.863,0.742,0.873,Brasília - DF,brasília - df
9,Curitiba (PR),0.823,0.850,0.768,0.855,Curitiba - PR,curitiba - pr

In [43]:
dados_final = pd.merge(sidra, atlas, left_on='municipio_lower', right_on='municipio_sidra_lower', how='inner')
dados_final = dados_final.drop(columns=['municipio_lower', 'municipio_y', 'municipio_sidra', 'municipio_sidra_lower'])
dados_final = dados_final.rename(columns={'municipio_x': 'municipio'})

display(dados_final.head())
display(dados_final.shape)
display(dados_final.info())

,cod_municipio,municipio,total_domicilios,perc_agua_rede,perc_esgoto_rede,perc_lixo_coletado,perc_alfabetizacao,renda_media,per_domicilio_urbano,IDHM,IDHM Renda,IDHM Educação,IDHM Longevidade
0,1100015,Alta Floresta D'Oeste - RO,7695,26.484730,0.467836,61.481481,91.59,1210.60,60.347074,0.641,0.657,0.526,0.763
1,1100023,Ariquemes - RO,34768,54.337322,1.993212,90.416475,94.08,1458.57,86.697717,0.702,0.716,0.600,0.806
2,1100031,Cabixi - RO,1967,39.298424,1.576004,61.057448,89.82,1323.79,53.186320,0.650,0.650,0.559,0.757
3,1100049,Cacoal - RO,31917,80.067049,67.189899,85.656547,93.71,1625.88,82.759216,0.718,0.727,0.620,0.821
4,1100056,Cerejeiras - RO,5873,49.480674,57.994211,87.042397,92.15,1554.33,88.835746,0.692,0.688,0.602,0.799

(5565, 13)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cod_municipio         5565 non-null   int64
 1   municipio             5565 non-null   object
 2   total_domicilios      5565 non-null   int64
 3   perc_agua_rede        5557 non-null   float64
 4   perc_esgoto_rede      5540 non-null   float64
 5   perc_lixo_coletado    5565 non-null   float64
 6   perc_alfabetizacao    5565 non-null   float64
 7   renda_media           5565 non-null   float64
 8   per_domicilio_urbano  5565 non-null   float64
 9   IDHM                  5565 non-null   float64
 10  IDHM Renda            5565 non-null   float64
 11  IDHM Educação         5565 non-null   float64
 12  IDHM Longevidade      5565 non-null   float64
dtypes: float64(10), int64(2), object(1)
memory usage: 565.3+ KB

None

In [44]:
print(dados_final.isna().sum())

cod_municipio            0
municipio                0
total_domicilios         0
perc_agua_rede           8
perc_esgoto_rede        25
perc_lixo_coletado       0
perc_alfabetizacao       0
renda_media              0
per_domicilio_urbano     0
IDHM                     0
IDHM Renda               0
IDHM Educação            0
IDHM Longevidade         0
dtype: int64

In [47]:
dados_final.to_csv(caminho / 'processados' / 'dados_final.csv', index=False)